"""
Random Forest risk classifier for SafeRoute.

This module is responsible for:
  1. Creating a reproducible synthetic/demo dataset of safety features.
  2. Training a RandomForestClassifier on that dataset.
  3. Exposing a predict() function used by the Flask API.

The model is trained ONCE when the module is first imported and reused for
every request, so we never retrain on each API call.

Dataset columns (features):
  crime_risk    0..100  (0 = safe, 100 = very risky)
  lighting_score 0..100  (0 = dark, 100 = well lit)
  traffic_level 0..100  (0 = empty, 100 = jammed)
  time_risk     0..100  (0 = safe hour, 100 = risky hour)
  road_risk     0..100  (0 = safe road, 100 = dangerous road)
  distance      meters  (raw segment length)

Target:
  risk          0 = lower risk, 1 = higher risk

The target is generated by a deterministic rule (not random) so the dataset
is reproducible and the model learns a meaningful mapping.
"""

from __future__ import annotations

import os
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib

MODEL_PATH = os.path.join(os.path.dirname(__file__), "risk_model.joblib")
DATASET_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "safety_data.csv")

FEATURES = ["crime_risk", "lighting_score", "traffic_level", "time_risk", "road_risk", "distance"]
TARGET = "risk"

# Number of synthetic rows generated for training.
N_SAMPLES = 4000
RANDOM_STATE = 42


def _generate_dataset(n_samples: int = N_SAMPLES, seed: int = RANDOM_STATE) -> pd.DataFrame:
    """Create a reproducible synthetic safety dataset.

    The target follows a deterministic rule so the classifier can learn it:
      risk increases with crime, traffic, time risk, road risk and distance,
      and decreases with better lighting.
    """
    rng = np.random.default_rng(seed)

    crime_risk = rng.uniform(0, 100, n_samples)
    lighting_score = rng.uniform(0, 100, n_samples)
    traffic_level = rng.uniform(0, 100, n_samples)
    time_risk = rng.uniform(0, 100, n_samples)
    road_risk = rng.uniform(0, 100, n_samples)
    distance = rng.uniform(20, 2000, n_samples)  # segment length in meters

    # Weighted risk score (0..100-ish). Lighting reduces risk.
    risk_score = (
        0.30 * crime_risk
        + 0.15 * traffic_level
        + 0.15 * time_risk
        + 0.25 * road_risk
        + 0.05 * (distance / 2000) * 100
        - 0.20 * lighting_score
    )
    # Threshold at 50 -> binary label. Add tiny noise so boundary isn't razor thin.
    noise = rng.normal(0, 3, n_samples)
    risk_label = (risk_score + noise > 50).astype(int)

    df = pd.DataFrame(
        {
            "crime_risk": np.round(crime_risk, 2),
            "lighting_score": np.round(lighting_score, 2),
            "traffic_level": np.round(traffic_level, 2),
            "time_risk": np.round(time_risk, 2),
            "road_risk": np.round(road_risk, 2),
            "distance": np.round(distance, 2),
            "risk": risk_label,
        }
    )
    return df


def get_or_create_dataset() -> pd.DataFrame:
    """Load the CSV if present, otherwise generate and persist it."""
    path = os.path.abspath(DATASET_PATH)
    if os.path.exists(path):
        return pd.read_csv(path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    df = _generate_dataset()
    df.to_csv(path, index=False)
    return df


def train_model(df: pd.DataFrame) -> tuple[RandomForestClassifier, float]:
    """Train a RandomForestClassifier and return (model, test_accuracy)."""
    X = df[FEATURES].values
    y = df[TARGET].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
    )

    clf = RandomForestClassifier(
        n_estimators=120,
        max_depth=None,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )
    clf.fit(X_train, y_train)

    preds = clf.predict(X_test)
    acc = accuracy_score(y_test, preds)
    return clf, acc


def load_or_train() -> tuple[RandomForestClassifier, float, pd.DataFrame]:
    """Load a persisted model if available, otherwise train and persist it."""
    if os.path.exists(MODEL_PATH):
        clf = joblib.load(MODEL_PATH)
        df = get_or_create_dataset()
        # Recompute accuracy quickly on the full dataset for display.
        acc = accuracy_score(df[TARGET].values, clf.predict(df[FEATURES].values))
        return clf, acc, df

    df = get_or_create_dataset()
    clf, acc = train_model(df)
    os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)
    joblib.dump(clf, MODEL_PATH)
    return clf, acc, df


# Eagerly train/load when the module is imported so the Flask app starts with
# a ready model. This is the "train once at startup" requirement.
_model, _accuracy, _dataset = load_or_train()


def get_model_info() -> dict:
    """Return metadata about the trained model (used by /api and /)."""
    return {
        "algorithm": "RandomForestClassifier",
        "n_estimators": _model.n_estimators,
        "features": FEATURES,
        "target": TARGET,
        "dataset_rows": int(len(_dataset)),
        "accuracy": round(float(_accuracy), 4),
    }


def predict(features: dict) -> dict:
    """Predict risk for a single segment given its safety features.

    Args:
        features: dict with keys crime_risk, lighting_score, traffic_level,
                  time_risk, road_risk, distance.

    Returns:
        dict with prediction (0/1), label (LOW/HIGH), and probability.
    """
    row = np.array(
        [
            [
                float(features["crime_risk"]),
                float(features["lighting_score"]),
                float(features["traffic_level"]),
                float(features["time_risk"]),
                float(features["road_risk"]),
                float(features["distance"]),
            ]
        ]
    )
    pred = int(_model.predict(row)[0])
    proba = _model.predict_proba(row)[0]
    confidence = float(max(proba))
    return {
        "prediction": pred,
        "label": "HIGH" if pred == 1 else "LOW",
        "confidence": round(confidence, 4),
        "probabilities": {"low": round(float(proba[0]), 4), "high": round(float(proba[1]), 4)},
    }
